name: Provision LaunchDarkly

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  REPO_NAME: ${{ github.event.repository.name }}
  OWNER: ${{ github.repository_owner }}

jobs:
  terraform:
    name: Terraform plan & apply
    runs-on: ubuntu-latest

    outputs:
      client_side_id: ${{ steps.tf_output.outputs.client_side_id }}

    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform init
        run: terraform init
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Terraform validate
        run: terraform validate

      - name: Terraform apply
        run: terraform apply -auto-approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_VAR_LAUNCHDARKLY_ACCESS_TOKEN: ${{ secrets.LD_ACCESS_TOKEN }}
          TF_VAR_project: ${{ env.OWNER }}-${{ env.REPO_NAME }}

      - name: Terraform output
        id: tf_output
        run: |
          CLIENT_SIDE_ID=$(terraform output -raw launchdarkly_client_side_id)
          echo "client_side_id=$CLIENT_SIDE_ID" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
